version: 2
jobs:
  build-push-image:
    machine: true
    steps:
      - checkout
      - run:
          name: install jq
          command: |
            sudo apt install jq
      - run: 
          name: install aws
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: build image
          command: "docker build -t myapp ."
      - run:
          name: ecr login
          command: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $AWS_ECR_ACCOUNT_URL/${MY_APP_PREFIX}
      - run:
          command: docker tag myapp $AWS_ECR_ACCOUNT_URL/${MY_APP_PREFIX}:${CIRCLE_SHA1}
      - run:
          command: docker push $AWS_ECR_ACCOUNT_URL/${MY_APP_PREFIX}:${CIRCLE_SHA1}
      -  run:
          name: crate new task definition
          command: |
            cat >> mytaskdefinition.json << EOF
            {
              "family": "${MY_ID}",
              "containerDefinitions": [{
                "name": "${SERVICE_NAME}",
                "image": "$AWS_ECR_ACCOUNT_URL/${MY_APP_PREFIX}:${CIRCLE_SHA1}",
                "portMappings": [{
                  "containerPort": 5000,
                  "hostPort": 0,
                  "protocol": "tcp"
                }],
                "essential": true
              }],
              "requiresCompatibilities": [
                "EC2"
              ],
              "cpu": "256",
              "memory": "512"
            }
            EOF
      - run:
          name: update task definition
          command: |
            aws ecs register-task-definition \
            --cli-input-json file://mytaskdefinition.json
      - run:
          name: get task descriptions
          command: |
            DECRIBED_SERVICE=$(aws ecs describe-task-definition --task-definition ${MY_ID});
            echo $DECRIBED_SERVICE
            TASK_REVISION=$(echo ${DECRIBED_SERVICE} | jq -r ".taskDefinition.revision")
            echo $TASK_REVISION
            aws ecs update-service --task-definition "${MY_ID}:${TASK_REVISION}" --cluster rdhrCluster --service ${SERVICE_NAME}
        
workflows:
  version: 2
  deploy-image:
    jobs:
      - build-push-image

