version: 2
jobs:
  build:
    machine: true
  steps:
    - checkout
    - run:
      command: sudo apt-get install python-pip python-dev
    - run:
      name: Install awscli
      command: sudo pip install awscli
workflows:
  # Name the workflow "welcome"
  deploy-image:
    # Run the welcome/run job in its own container
    jobs:
      - build-push
